day = input("Введите дату: ")
job = input("Введите задачу: ")
Tomorrow = input("Введите дату: ")
jobes = input("Введите задачу: ")
data = input("Введите дату: ")
joob = input("Введите задачу: ")
print(day, job)
print(Tomorrow, jobes )
print(data, joob)